/**
 * dump-schema.mjs — 从数据库反向导出完整 DDL（表格 + RPC）
 *
 * 输出：一个 .sql 文件，包含所有用户表定义、序列、索引、
 *       RLS 策略、RPC 函数定义。不含数据。
 *
 * 用法：export SUPABASE_DB_PASSWORD=... && node scripts/dump-schema.mjs
 */

import pg from 'pg'
import { writeFileSync } from 'fs'

const { Client } = pg

const client = new Client({
  host: 'db.iiiyoafpzfqxpaqheojg.supabase.co',
  database: 'postgres',
  user: 'postgres',
  password: process.env.SUPABASE_DB_PASSWORD,
  port: 5432,
  ssl: { rejectUnauthorized: false },
})

await client.connect()

const lines = []
const w = (s = '') => lines.push(s)

w('-- ============================================================')
w('-- shsg8c1wiki — Full Database Schema')
w('-- Auto-generated by scripts/dump-schema.mjs')
w(`-- Generated at: ${new Date().toISOString()}`)
w('-- ============================================================')
w('')

// ── 排除的系统表 ──
const EXCLUDED_TABLES = [
  '_analytics', '_prisma_migrations', 'audit_log_entries',
  'flow_state', 'identities', 'instances', 'mfa_amr_claims',
  'mfa_challenges', 'mfa_factors', 'mfa_factors',
  'one_time_tokens', 'refresh_tokens', 'saml_providers',
  'saml_relay_states', 'schema_migrations', 'sessions',
  'sso_domains', 'sso_providers', 'users',
]

// ── 1. Sequences ──
w('-- ============================================================')
w('-- SEQUENCES')
w('-- ============================================================')
w('')

const { rows: seqRows } = await client.query(`
  SELECT DISTINCT sequencename
  FROM pg_catalog.pg_sequences
  WHERE schemaname = 'public'
  ORDER BY sequencename
`)

for (const seq of seqRows) {
  w(`CREATE SEQUENCE IF NOT EXISTS ${seq.sequencename} START 1;`)
}

// ── 2. Tables ──
w('-- ============================================================')
w('-- TABLES')
w('-- ============================================================')
w('')

const { rows: tableRows } = await client.query(`
  SELECT tablename
  FROM pg_catalog.pg_tables
  WHERE schemaname = 'public'
    AND tablename != ALL($1)
  ORDER BY tablename
`, [EXCLUDED_TABLES])

for (const { tablename } of tableRows) {
  w(`-- ── ${tablename} ──`)

  // Columns
  const { rows: cols } = await client.query(`
    SELECT
      a.attname AS column_name,
      pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
      a.attnotnull AS not_null,
      pg_catalog.pg_get_expr(d.adbin, d.adrelid) AS default_value
    FROM pg_catalog.pg_attribute a
    LEFT JOIN pg_catalog.pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
    WHERE a.attrelid = (SELECT oid FROM pg_class WHERE relname = $1 AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public'))
      AND a.attnum > 0
      AND NOT a.attisdropped
    ORDER BY a.attnum
  `, [tablename])

  // Primary key
  const { rows: pks } = await client.query(`
    SELECT a.attname
    FROM pg_index i
    JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
    WHERE i.indrelid = (SELECT oid FROM pg_class WHERE relname = $1 AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public'))
      AND i.indisprimary
    ORDER BY a.attnum
  `, [tablename])

  // Foreign keys
  const { rows: fks } = await client.query(`
    SELECT
      conname,
      pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con
    WHERE con.conrelid = (SELECT oid FROM pg_class WHERE relname = $1 AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public'))
      AND con.contype = 'f'
    ORDER BY conname
  `, [tablename])

  // Check constraints
  const { rows: checks } = await client.query(`
    SELECT
      conname,
      pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con
    WHERE con.conrelid = (SELECT oid FROM pg_class WHERE relname = $1 AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public'))
      AND con.contype = 'c'
    ORDER BY conname
  `, [tablename])

  // Unique constraints
  const { rows: uniques } = await client.query(`
    SELECT
      conname,
      pg_get_constraintdef(con.oid) AS def
    FROM pg_constraint con
    WHERE con.conrelid = (SELECT oid FROM pg_class WHERE relname = $1 AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public'))
      AND con.contype = 'u'
    ORDER BY conname
  `, [tablename])

  // Build CREATE TABLE
  w(`CREATE TABLE IF NOT EXISTS ${tablename} (`)

  const colDefs = []
  for (const col of cols) {
    let def = `  ${col.column_name} ${col.data_type}`
    const pkCol = pks.find(p => p.attname === col.column_name)
    if (pkCol) {
      // PK handled separately below
    }
    if (col.not_null && !pkCol) {
      def += ' NOT NULL'
    }
    if (col.default_value) {
      // pg_get_expr returns things like "nextval('seq'::regclass)" or "'value'::type"
      def += ` DEFAULT ${col.default_value}`
    }
    colDefs.push(def)
  }

  // Primary key constraint
  if (pks.length > 0) {
    colDefs.push(`  PRIMARY KEY (${pks.map(p => p.attname).join(', ')})`)
  }

  // Foreign keys
  for (const fk of fks) {
    colDefs.push(`  CONSTRAINT ${fk.conname} ${fk.def}`)
  }

  // Check constraints
  for (const chk of checks) {
    colDefs.push(`  CONSTRAINT ${chk.conname} ${chk.def}`)
  }

  // Unique constraints (excluding PK which was already added)
  for (const uq of uniques) {
    colDefs.push(`  CONSTRAINT ${uq.conname} ${uq.def}`)
  }

  w(colDefs.join(',\n'))
  w(');')
  w('')
}

// ── 3. Indexes ──
w('-- ============================================================')
w('-- INDEXES')
w('-- ============================================================')
w('')

const { rows: idxRows } = await client.query(`
  SELECT
    i.indexrelid::regclass AS index_name,
    t.relname AS table_name,
    pg_get_indexdef(i.indexrelid) AS def
  FROM pg_index i
  JOIN pg_class t ON i.indrelid = t.oid
  JOIN pg_namespace n ON t.relnamespace = n.oid
  WHERE n.nspname = 'public'
    AND t.relname != ALL($1)
    AND NOT i.indisprimary
  ORDER BY t.relname, i.indexrelid::regclass::text
`, [EXCLUDED_TABLES])

for (const idx of idxRows) {
  if (idx.def.includes('CREATE UNIQUE INDEX')) {
    w(idx.def.replace('CREATE UNIQUE INDEX', 'CREATE UNIQUE INDEX IF NOT EXISTS') + ';')
  } else {
    w(idx.def.replace('CREATE INDEX', 'CREATE INDEX IF NOT EXISTS') + ';')
  }
}
if (idxRows.length === 0) w('-- (none)')
w('')

// ── 4. RLS ──
w('-- ============================================================')
w('-- ROW LEVEL SECURITY')
w('-- ============================================================')
w('')

for (const { tablename } of tableRows) {
  const { rows: rlsRows } = await client.query(`
    SELECT relrowsecurity
    FROM pg_class
    WHERE relname = $1 AND relnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'public')
  `, [tablename])

  if (rlsRows.length > 0 && rlsRows[0].relrowsecurity) {
    w(`ALTER TABLE ${tablename} ENABLE ROW LEVEL SECURITY;`)
  }
}
w('')

// ── 5. Policies ──
w('-- ============================================================')
w('-- RLS POLICIES')
w('-- ============================================================')
w('')

const { rows: polRows } = await client.query(`
  SELECT
    p.polname,
    t.relname AS table_name,
    CASE p.polcmd
      WHEN 'r' THEN 'SELECT'
      WHEN 'a' THEN 'INSERT'
      WHEN 'w' THEN 'UPDATE'
      WHEN 'd' THEN 'DELETE'
      WHEN '*' THEN 'ALL'
    END AS cmd,
    pg_get_expr(p.polqual, p.polrelid) AS using_expr,
    pg_get_expr(p.polwithcheck, p.polrelid) AS withcheck_expr,
    p.polpermissive
  FROM pg_policy p
  JOIN pg_class t ON p.polrelid = t.oid
  JOIN pg_namespace n ON t.relnamespace = n.oid
  WHERE n.nspname = 'public'
    AND t.relname != ALL($1)
  ORDER BY t.relname, p.polname
`, [EXCLUDED_TABLES])

for (const pol of polRows) {
  w(`DROP POLICY IF EXISTS "${pol.polname}" ON ${pol.table_name};`)
  let stmt = `CREATE POLICY "${pol.polname}" ON ${pol.table_name}`
  if (pol.polpermissive === false) stmt += ' AS RESTRICTIVE'
  stmt += ` FOR ${pol.cmd}`
  if (pol.using_expr) stmt += ` USING (${pol.using_expr})`
  if (pol.withcheck_expr) stmt += ` WITH CHECK (${pol.withcheck_expr})`
  w(stmt + ';')
}
if (polRows.length === 0) w('-- (none)')
w('')

// ── 6. Functions ──
w('-- ============================================================')
w('-- FUNCTIONS / RPC')
w('-- ============================================================')
w('')

const { rows: funcRows } = await client.query(`
  SELECT
    p.proname AS name,
    pg_get_functiondef(p.oid) AS def
  FROM pg_proc p
  JOIN pg_namespace n ON p.pronamespace = n.oid
  WHERE n.nspname = 'public'
    AND p.prokind = 'f'
  ORDER BY p.proname
`)

for (const fn of funcRows) {
  w(fn.def)
  w('')
}

// ── 7. GRANTs ──
w('-- ============================================================')
w('-- GRANTS')
w('-- ============================================================')
w('')

const { rows: grantRows } = await client.query(`
  SELECT
    p.proname AS function_name,
    pg_get_function_identity_arguments(p.oid) AS args
  FROM pg_proc p
  JOIN pg_namespace n ON p.pronamespace = n.oid
  LEFT JOIN pg_proc p2 ON p2.oid = p.oid
  WHERE n.nspname = 'public'
    AND p.prokind = 'f'
  ORDER BY p.proname
`)

for (const fn of grantRows) {
  // 大多数 RPC 都授予了 PUBLIC，统一输出
  w(`GRANT EXECUTE ON FUNCTION ${fn.function_name}(${fn.args || ''}) TO PUBLIC;`)
}

writeFileSync('schema.sql', lines.join('\n'), 'utf8')
console.log(`✓ 已生成 schema.sql（${lines.length} 行，${Buffer.byteLength(lines.join('\n'), 'utf8')} 字节）`)

await client.end()
