// Auto-generated by scripts/generate-person-ts.js
// Do not edit manually.

import type { PersonRegistry } from '@/lib/people'

export const registry: PersonRegistry = {
  "version": 1,
  "students": [
    {
      "name": "孔令仪",
      "initials": "kly",
      "pinyin": "kong ling yi",
      "pinyinPrefix": "kong",
      "pinyinRestInitials": "ly",
      "hyphenForm": "kong-ly",
      "oldSlug": "people/kong-lingyi",
      "newSlug": "people/kly",
      "gender": "女"
    },
    {
      "name": "李跃然",
      "initials": "lyr",
      "pinyin": "li yue ran",
      "pinyinPrefix": "li",
      "pinyinRestInitials": "yr",
      "hyphenForm": "li-yr",
      "oldSlug": "people/li-yueran",
      "newSlug": "people/lyr",
      "gender": "女"
    },
    {
      "name": "薛旻喆",
      "initials": "xmz",
      "pinyin": "xue min zhe",
      "pinyinPrefix": "xue",
      "pinyinRestInitials": "mz",
      "hyphenForm": "xue-mz",
      "oldSlug": "people/xue-minzhe",
      "newSlug": "people/xmz",
      "gender": "女"
    },
    {
      "name": "张晋苏",
      "initials": "zjs",
      "pinyin": "zhang jin su",
      "pinyinPrefix": "zhang",
      "pinyinRestInitials": "js",
      "hyphenForm": "zhang-js",
      "oldSlug": "people/zhang-jinsu",
      "newSlug": "people/zjs",
      "gender": "女"
    },
    {
      "name": "周方予",
      "initials": "zfy",
      "pinyin": "zhou fang yu",
      "pinyinPrefix": "zhou",
      "pinyinRestInitials": "fy",
      "hyphenForm": "zhou-fy",
      "oldSlug": "people/zhou-fangyu",
      "newSlug": "people/zfy",
      "gender": "女"
    },
    {
      "name": "陈文一",
      "initials": "cwy",
      "pinyin": "chen wen yi",
      "pinyinPrefix": "chen",
      "pinyinRestInitials": "wy",
      "hyphenForm": "chen-wy",
      "oldSlug": "people/chen-wenyi",
      "newSlug": "people/cwy",
      "gender": "男"
    },
    {
      "name": "陈希言",
      "initials": "cxy",
      "pinyin": "chen xi yan",
      "pinyinPrefix": "chen",
      "pinyinRestInitials": "xy",
      "hyphenForm": "chen-xy",
      "oldSlug": "people/chen-xiyan",
      "newSlug": "people/cxy",
      "gender": "男"
    },
    {
      "name": "桂锦煊",
      "initials": "gjx",
      "pinyin": "gui jin xuan",
      "pinyinPrefix": "gui",
      "pinyinRestInitials": "jx",
      "hyphenForm": "gui-jx",
      "oldSlug": "people/gui-jinxuan",
      "newSlug": "people/gjx",
      "gender": "男"
    },
    {
      "name": "蒋润齐",
      "initials": "jrq",
      "pinyin": "jiang run qi",
      "pinyinPrefix": "jiang",
      "pinyinRestInitials": "rq",
      "hyphenForm": "jiang-rq",
      "oldSlug": "people/jiang-runqi",
      "newSlug": "people/jrq",
      "gender": "男"
    },
    {
      "name": "李澈",
      "initials": "lc",
      "pinyin": "li che",
      "pinyinPrefix": "li",
      "pinyinRestInitials": "c",
      "hyphenForm": "li-c",
      "oldSlug": "people/li-che",
      "newSlug": "people/lc",
      "gender": "男"
    },
    {
      "name": "李裕泽",
      "initials": "lyz",
      "pinyin": "li yu ze",
      "pinyinPrefix": "li",
      "pinyinRestInitials": "yz",
      "hyphenForm": "li-yz",
      "oldSlug": "people/li-yuze",
      "newSlug": "people/lyz",
      "gender": "男"
    },
    {
      "name": "林沁圻",
      "initials": "lqq",
      "pinyin": "lin qin qi",
      "pinyinPrefix": "lin",
      "pinyinRestInitials": "qq",
      "hyphenForm": "lin-qq",
      "oldSlug": "people/lin-qinqi",
      "newSlug": "people/lqq",
      "gender": "男"
    },
    {
      "name": "龙沛霖",
      "initials": "lpl",
      "pinyin": "long pei lin",
      "pinyinPrefix": "long",
      "pinyinRestInitials": "pl",
      "hyphenForm": "long-pl",
      "oldSlug": "people/long-peilin",
      "newSlug": "people/lpl",
      "gender": "男"
    },
    {
      "name": "罗熙昊",
      "initials": "lxh",
      "pinyin": "luo xi hao",
      "pinyinPrefix": "luo",
      "pinyinRestInitials": "xh",
      "hyphenForm": "luo-xh",
      "oldSlug": "people/luo-xihao",
      "newSlug": "people/lxh",
      "gender": "男"
    },
    {
      "name": "闵汇杰",
      "initials": "mhj",
      "pinyin": "min hui jie",
      "pinyinPrefix": "min",
      "pinyinRestInitials": "hj",
      "hyphenForm": "min-hj",
      "oldSlug": "people/min-huijie",
      "newSlug": "people/mhj",
      "gender": "男"
    },
    {
      "name": "童麒宇",
      "initials": "tqy",
      "pinyin": "tong qi yu",
      "pinyinPrefix": "tong",
      "pinyinRestInitials": "qy",
      "hyphenForm": "tong-qy",
      "oldSlug": "people/tong-qiyu",
      "newSlug": "people/tqy",
      "gender": "男"
    },
    {
      "name": "王禹程",
      "initials": "wyc",
      "pinyin": "wang yu cheng",
      "pinyinPrefix": "wang",
      "pinyinRestInitials": "yc",
      "hyphenForm": "wang-yc",
      "oldSlug": "people/wang-yucheng",
      "newSlug": "people/wyc",
      "gender": "男"
    },
    {
      "name": "王梓",
      "initials": "wz",
      "pinyin": "wang zi",
      "pinyinPrefix": "wang",
      "pinyinRestInitials": "z",
      "hyphenForm": "wang-z",
      "oldSlug": "people/wang-zi",
      "newSlug": "people/wz",
      "gender": "男"
    },
    {
      "name": "闻思奕",
      "initials": "wsy",
      "pinyin": "wen si yi",
      "pinyinPrefix": "wen",
      "pinyinRestInitials": "sy",
      "hyphenForm": "wen-sy",
      "oldSlug": "people/wen-siyi",
      "newSlug": "people/wsy",
      "gender": "男"
    },
    {
      "name": "肖逸辰",
      "initials": "xyc",
      "pinyin": "xiao yi chen",
      "pinyinPrefix": "xiao",
      "pinyinRestInitials": "yc",
      "hyphenForm": "xiao-yc",
      "oldSlug": "people/xiao-yichen",
      "newSlug": "people/xyc",
      "gender": "男"
    },
    {
      "name": "许皓麟",
      "initials": "xhl",
      "pinyin": "xu hao lin",
      "pinyinPrefix": "xu",
      "pinyinRestInitials": "hl",
      "hyphenForm": "xu-hl",
      "oldSlug": "people/xu-haolin",
      "newSlug": "people/xhl",
      "gender": "男"
    },
    {
      "name": "许梓楠",
      "initials": "xzn",
      "pinyin": "xu zi nan",
      "pinyinPrefix": "xu",
      "pinyinRestInitials": "zn",
      "hyphenForm": "xu-zn",
      "oldSlug": "people/xu-zinan",
      "newSlug": "people/xzn",
      "gender": "男"
    },
    {
      "name": "杨佳瑞",
      "initials": "yjr",
      "pinyin": "yang jia rui",
      "pinyinPrefix": "yang",
      "pinyinRestInitials": "jr",
      "hyphenForm": "yang-jr",
      "oldSlug": "people/yang-jiarui",
      "newSlug": "people/yjr",
      "gender": "男"
    },
    {
      "name": "郑鸣泽",
      "initials": "zmz",
      "pinyin": "zheng ming ze",
      "pinyinPrefix": "zheng",
      "pinyinRestInitials": "mz",
      "hyphenForm": "zheng-mz",
      "oldSlug": "people/zheng-mingze",
      "newSlug": "people/zmz",
      "gender": "男"
    },
    {
      "name": "周义畯",
      "initials": "zyj",
      "pinyin": "zhou yi jun",
      "pinyinPrefix": "zhou",
      "pinyinRestInitials": "yj",
      "hyphenForm": "zhou-yj",
      "oldSlug": "people/zhou-yijun",
      "newSlug": "people/zyj",
      "gender": "男"
    }
  ],
  "teachers": [
    {
      "name": "蒋威",
      "initials": "jw",
      "pinyin": "jiang wei",
      "pinyinPrefix": "jiang",
      "pinyinRestInitials": "w",
      "hyphenForm": "jiang-w",
      "subject": "数学"
    },
    {
      "name": "汪妍",
      "initials": "wy",
      "pinyin": "wang yan",
      "pinyinPrefix": "wang",
      "pinyinRestInitials": "y",
      "hyphenForm": "wang-y",
      "subject": "语文"
    },
    {
      "name": "杨一树",
      "initials": "yys",
      "pinyin": "yang yi shu",
      "pinyinPrefix": "yang",
      "pinyinRestInitials": "ys",
      "hyphenForm": "yang-ys",
      "subject": "英语"
    },
    {
      "name": "徐子及",
      "initials": "xzj",
      "pinyin": "xu zi ji",
      "pinyinPrefix": "xu",
      "pinyinRestInitials": "zj",
      "hyphenForm": "xu-zj",
      "subject": "物理"
    },
    {
      "name": "李锋云",
      "initials": "lfy",
      "pinyin": "li feng yun",
      "pinyinPrefix": "li",
      "pinyinRestInitials": "fy",
      "hyphenForm": "li-fy",
      "subject": "化学"
    },
    {
      "name": "徐子蓝",
      "initials": "xzl",
      "pinyin": "xu zi lan",
      "pinyinPrefix": "xu",
      "pinyinRestInitials": "zl",
      "hyphenForm": "xu-zl",
      "subject": "生物"
    },
    {
      "name": "邱宛霖",
      "initials": "qwl",
      "pinyin": "qiu wan lin",
      "pinyinPrefix": "qiu",
      "pinyinRestInitials": "wl",
      "hyphenForm": "qiu-wl",
      "subject": "政治/班主任"
    },
    {
      "name": "钱涛",
      "initials": "qt",
      "pinyin": "qian tao",
      "pinyinPrefix": "qian",
      "pinyinRestInitials": "t",
      "hyphenForm": "qian-t",
      "subject": "信息"
    },
    {
      "name": "张洋洋",
      "initials": "zyy",
      "pinyin": "zhang yang yang",
      "pinyinPrefix": "zhang",
      "pinyinRestInitials": "yy",
      "hyphenForm": "zhang-yy",
      "subject": "音乐"
    },
    {
      "name": "严亮",
      "initials": "yl",
      "pinyin": "yan liang",
      "pinyinPrefix": "yan",
      "pinyinRestInitials": "l",
      "hyphenForm": "yan-l",
      "subject": "体育"
    },
    {
      "name": "冯祖鸣",
      "initials": "fzm",
      "pinyin": "feng zu ming",
      "pinyinPrefix": "feng",
      "pinyinRestInitials": "zm",
      "hyphenForm": "feng-zm",
      "subject": "数学拓展"
    }
  ],
  "oldToNewSlug": {
    "people/kong-lingyi": "people/kly",
    "people/li-yueran": "people/lyr",
    "people/xue-minzhe": "people/xmz",
    "people/zhang-jinsu": "people/zjs",
    "people/zhou-fangyu": "people/zfy",
    "people/chen-wenyi": "people/cwy",
    "people/chen-xiyan": "people/cxy",
    "people/gui-jinxuan": "people/gjx",
    "people/jiang-runqi": "people/jrq",
    "people/li-che": "people/lc",
    "people/li-yuze": "people/lyz",
    "people/lin-qinqi": "people/lqq",
    "people/long-peilin": "people/lpl",
    "people/luo-xihao": "people/lxh",
    "people/min-huijie": "people/mhj",
    "people/tong-qiyu": "people/tqy",
    "people/wang-yucheng": "people/wyc",
    "people/wang-zi": "people/wz",
    "people/wen-siyi": "people/wsy",
    "people/xiao-yichen": "people/xyc",
    "people/xu-haolin": "people/xhl",
    "people/xu-zinan": "people/xzn",
    "people/yang-jiarui": "people/yjr",
    "people/zheng-mingze": "people/zmz",
    "people/zhou-yijun": "people/zyj"
  }
}
